#!/bin/bash
set -e
mkdir -p /var/log/nginx
#for some reason passenger nginx always logs to /var/log/nginx/error.log even if error_log points elsewhere so this is a workaround
ln -sf /dev/stdout /var/log/nginx/access.log
ln -sf /dev/stderr /var/log/nginx/error.log
#Open file descriptors and redirect nginx's stdout and stdin to two pylogger processes
exec 3> >(pylogger -t nginx -p 6 -F 128)
exec 4> >(pylogger -t nginx -p 3 -F 128)
exec /usr/sbin/nginx 1>&3 2>&4
